#!/bin/bash

prg=../../try

# i=0
for t in Test/Test_* ; do
    cd Test
    x=${t##*/}
    if [ $x == "run" ]; then
        continue
    fi
    # echo $x
    cd "$x" || continue
    $prg <inp 2>&1 >out
    diff -q -w exp out 2>&1 >/dev/null || echo ${t##*/} failed >&2
    # ((i++))
    cd ../..
done
